//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Desktop.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        public string CompanyName { get; internal set; }
        public string DirectorName { get; internal set; }
        public string CompanyAddress { get; internal set; }
        public string INN { get; internal set; }
        public string KPP { get; internal set; }
        public string BIK { get; internal set; }
        public string PAcc { get; internal set; }
        public string CAcc { get; internal set; }
        public string Bank { get; internal set; }
        public string SaveFilePath { get; internal set; }
        public string UserName { get; internal set; }
        public string Password { get; internal set; }
    }
}
